# Generated by Django 4.2 on 2024-10-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscribed_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
