# Generated by Django 4.2 on 2024-10-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='TagPost',
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='length_time',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='pre_view',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
