# Generated by Django 4.2 on 2024-10-12 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0002_rename_tags_tagpost_alter_video_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagpost',
            name='tag_slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.CreateModel(
            name='UserVideoRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.SmallIntegerField(choices=[(1, 'Like'), (-1, 'Dislike')], null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.video')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=300)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='service.comment')),
                ('user_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_com', to=settings.AUTH_USER_MODEL)),
                ('video_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vid_com', to='service.video')),
            ],
        ),
    ]
