# Generated by Django 4.1 on 2024-12-13 17:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_playlistlike_delete_addauthorlisttouser'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesVids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=50)),
                ('cat_slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='the_video',
            field=models.FileField(blank=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi'])]),
        ),
    ]
