# Generated by Django 4.1 on 2024-12-13 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_categoriesvids_alter_video_the_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='cats',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, related_name='video_cats', to='service.categoriesvids'),
        ),
    ]
