# Generated by Django 4.1 on 2024-11-15 15:45

import django.core.validators
from django.db import migrations, models
import service.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_comment_level_comment_lft_comment_rght_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='the_video',
            field=models.FileField(blank=True, upload_to=service.models.get_path_upload_video, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi'])]),
        ),
    ]
